metadata:
  name: integrationArtifactUpdateConfiguration
  description: Update integration flow configuration parameters.
  longDescription: |
    With this step, you can update the value of a configuration parameter of a designtime integration flow using the OData API. For more information on the SAP Cloud Integration remote API for deploying an integration artifact, see [Integration Content](https://help.sap.com/viewer/368c481cd6954bdfa5d0435479fd4eaf/Cloud/en-US/83733a65c0214aa6acba035e8640bb5a.html) on the SAP Help Portal.

spec:
  inputs:
    secrets:
      - name: cpiApiServiceKeyCredentialsId
        description: Jenkins secret text credential ID containing the service key to the Process Integration Runtime service instance of plan 'api'.
        type: jenkins
    params:
      - name: apiServiceKey
        type: string
        description: Service key JSON string to access the Process Integration Runtime service instance of plan 'api'.
        scope:
          - PARAMETERS
        mandatory: true
        secret: true
        resourceRef:
          - name: cpiApiServiceKeyCredentialsId
            type: secret
            param: apiServiceKey
      - name: integrationFlowId
        type: string
        description: Specifies the ID of the integration flow artifact.
        scope:
          - PARAMETERS
          - GENERAL
          - STAGES
          - STEPS
        mandatory: true
      - name: integrationFlowVersion
        type: string
        description: Specifies the version of the integration flow artifact.
        scope:
          - PARAMETERS
          - GENERAL
          - STAGES
          - STEPS
        mandatory: true
      - name: parameterKey
        type: string
        description: Specifies the externalized parameter name.
        scope:
          - PARAMETERS
          - STAGES
          - STEPS
        mandatory: true
      - name: parameterValue
        type: string
        description: Specifies the externalized parameter value.
        scope:
          - PARAMETERS
          - STAGES
          - STEPS
        mandatory: true
